# Copyright (c) 2024-2025 Mifuyu (mifuyutsuki@proton.me)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

from typing import Optional, Any, Union, Self
from datetime import timezone
from enum import StrEnum
import csv
import yaml
import uuid

import attrs
import interactions as ipy
import sqlalchemy as sa
from sqlalchemy import select, update, delete, literal
from sqlalchemy.ext.asyncio import AsyncSession

from mitsuki.utils import option, ratio, process_text
from mitsuki.lib.userdata import begin_session, AsDict, sa_insert as insert
from mitsuki.lib.commands import CustomID

from mitsuki.core.settings import get_setting, Settings
from mitsuki.core.submitter import BaseSubmitter
from mitsuki.core.gacha import CardRarity, Card


class CardSubmitterErrors(StrEnum):
  FIELD = "Missing or invalid field"
  RARITY = "Rarity not defined"


@attrs.define(kw_only=True)
class CardSubmitter(BaseSubmitter):
  to_add: list[Card] = attrs.field(factory=list)
  to_edit: list[Card] = attrs.field(factory=list)
  to_delist: list[Card] = attrs.field(factory=list)

  original_count: int = attrs.field(default=0)
  edit_count: int = attrs.field(default=0)
  relist_count: int = attrs.field(default=0)

  error_counts: dict[CardSubmitterErrors, int] = attrs.field(factory=dict)


  @property
  def add_count(self):
    return len(self.to_add)


  @property
  def delist_count(self):
    return len(self.to_delist) + len([c for c in self.to_edit if c.unlisted])


  @property
  def after_count(self):
    return self.original_count + len(self.to_add) - len(self.to_delist)


  def __attrs_post_init__(self):
    for e in CardSubmitterErrors:
      self.error_counts[e.value] = 0


  @classmethod
  async def from_rosc2y_yaml(cls, data: dict[str, dict[str, Any]]):
    """
    Create a gacha card submitter from a yaml generated by rosc2y, an internal
    csv-to-yaml tool developed for Mitsuki gacha use.

    Args:
      data: Card data in the format {id: {<field>: <value>, ...}, ...}

    Returns:
      Instance of this submitter
    """
    rarities = {r.rarity: r for r in await CardRarity.fetch_all()}
    fetch_cards = await Card.fetch_all(unobtained=True, private=True)
    cards = {c.id: c for c in await Card.fetch_all(unobtained=True, private=True)}

    result = cls()
    result.original_count = len([c for c in fetch_cards if not c.unlisted])

    for card_data_id, card_data in data.items():
      try:
        this_card = Card(
          id=card_data_id, name=card_data["name"], rarity=int(card_data["rarity"]),
          type=card_data["type"], series=card_data["series"], image=card_data.get("image", None),
          limited=bool(card_data.get("limited")), locked=bool(card_data.get("locked")),
          unlisted=bool(card_data.get("unlisted")), convert_to=card_data.get("convert_to", {}),
        )
      except (KeyError, ValueError):
        result.error_counts[CardSubmitterErrors.FIELD] += 1
        continue

      if this_card.rarity not in rarities:
        result.error_counts[CardSubmitterErrors.RARITY] += 1
        continue

      if card_data_id not in cards:
        result.to_add.append(this_card)
      elif this_card != (existing_card := cards.pop(card_data_id)):
        # If equal, do nothing, but still pop the card from `cards`
        if existing_card.unlisted and not this_card.unlisted:
          result.relist_count += 1
        else:
          result.edit_count += 1
        result.to_edit.append(this_card)

    result.to_delist.extend(cards.values())
    result.save()
    return result


  async def execute(self, session: AsyncSession):
    for card in self.to_add:
      await card.add(session)
    for card in self.to_edit:
      await card.update(session)
    for card in self.to_delist:
      card.unlisted = True
      await card.update(session)