# Copyright (c) 2024-2026 Mifuyu (mifuyutsuki@proton.me)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

from typing import Optional, Any, Union, Self
from datetime import timezone
from enum import StrEnum
import csv
import yaml
import uuid

import attrs
import interactions as ipy
import sqlalchemy as sa
from sqlalchemy import select, update, delete, literal
from sqlalchemy.ext.asyncio import AsyncSession

from mitsuki.utils import option, ratio, process_text
from mitsuki.lib.userdata import begin_session, AsDict, sa_insert as insert
from mitsuki.lib.commands import CustomID

from mitsuki.core.settings import get_setting, Settings
from mitsuki.core.submitter import BaseSubmitter
from mitsuki.core.gacha import CardCollection


@attrs.define()
class CardPackSubmitterEntry:
  collection: CardCollection
  category_ids: list[str] = attrs.field(factory=list)
  card_ids: list[str] = attrs.field(factory=list)
  card_regexes: list[str] = attrs.field(factory=list)


@attrs.define(kw_only=True)
class CardPackSubmitter(BaseSubmitter):
  to_add: list[CardPackSubmitterEntry] = attrs.field(factory=list)
  to_edit: list[CardPackSubmitterEntry] = attrs.field(factory=list)
  to_remove: list[CardPackSubmitterEntry] = attrs.field(factory=list)

  original_count: int = attrs.field(default=0)
  edit_count: int = attrs.field(default=0)
  error_counts: int = attrs.field(default=0)


  @property
  def add_count(self):
    return len(self.to_add)
  

  @property
  def remove_count(self):
    return len(self.to_remove)


  @property
  def after_count(self):
    return self.original_count + len(self.to_add)
  

  @classmethod
  async def from_pack2y_yaml(cls, data: dict[str, dict[str, Any]]):
    """
    Create a card pack submitter from a yaml generated by pack2y, a csv-to-yaml tool for Mitsuki Gacha pack updates.

    The data follows the format {<id>: {<field>: <value>, ...}, ...}, where the object inside each id corresponds to
    data for each card pack. The following fields are available (besides the card pack id):
    - name: str (required)
    - description: str
    - rollable: bool (default false)
    - discoverable: bool (default false)
    - show_counts: bool (default false)
    - category: [str]
    - cards: [str]
    - cards_regex: [str]

    Args:
      data: Card pack data
    """
    existing = {c.id: c for c in await CardCollection.fetch_all(private=True)}
    result = cls()
    result.original_count = len(existing)

    for pack_id, pack in data.items():
      try:
        collection = CardCollection(
          id=pack_id, name=pack["name"], description=pack.get("description"), rollable=bool(pack.get("rollable")),
          discoverable=bool(pack.get("discoverable")), show_counts=bool(pack.get("show_counts")),
        )
        entry = CardPackSubmitterEntry(
          collection=collection, category_id=pack.get("category"), card_ids=pack.get("cards"),
          card_regexes=pack.get("cards_regex")
        )
      except (KeyError, ValueError):
        error_counts += 1
        continue

      if entry.collection.id not in existing:
        result.to_add.append(entry)
      elif entry.collection != existing.pop(entry.collection.id, None):
        result.to_edit.append(entry)

    for remaining in existing.values():
      result.to_remove.append(remaining)

    result.save()
    return result


  async def execute(self, session: AsyncSession):
    for entry in self.to_add:
      collection = entry.collection
      await collection.add(session)
      if card_ids := entry.card_ids:
        await collection.add_cards(session, card_ids)
      if card_regexes := entry.card_regexes:
        await collection.add_cards_by_grep_id(session, card_regexes)
      if entry.category_ids:
        await collection.add_to_category(entry.category_ids)

    for entry in self.to_edit:
      collection = entry.collection
      await collection.clear(session)
      if card_ids := entry.card_ids:
        await collection.add_cards(session, card_ids)
      if card_regexes := entry.card_regexes:
        await collection.add_cards_by_grep_id(session, card_regexes)
      if entry.category_ids:
        await collection.add_to_category(entry.category_ids)

    # Some collections are used by a season, so don't do this just yet
    # for entry in self.to_remove:
    #   collection = entry.collection
    #   await collection.delete(session)